New: Abort when no enabled Wi-Fi interfaces are configured

diff --git a/initscript b/initscript
--- a/initscript
+++ b/initscript
@@ -7,13 +7,22 @@ START=99
 NAME=rrm_nr
 USE_PROCD=1
 
-function wait_until_all_wireless_interfaces_are_up() {
-	function are_all_wireless_interfaces_up() {
-		local count_configured=$( uci show wireless | grep wifi-iface | wc -l)
-		local count_up=$( ubus list hostapd.* | wc -l )
-		local count_disabled=$( uci show wireless | grep .disabled='1' | wc -l )
+function count_enabled_wifi_interfaces() {
+	local count_configured=$( uci -q show wireless | grep wifi-iface | wc -l)
+	local count_disabled=$( uci -q show wireless | grep .disabled='1' | wc -l )
+	printf "$(( count_configured - count_disabled ))"
+}
 
-		[ $(( count_configured - count_disabled  )) -eq $count_up ] && return 0 || return 1
+function abort_when_no_enabled_wifi_interfaces() {
+	[ $( count_enabled_wifi_interfaces ) -gt 0 ] && return 0
+	logger -t "${NAME}" -pdaemon.error "No enabled Wi-Fi interfaces found"
+	exit 1
+}
+
+function wait_until_all_enabled_wifi_interfaces_are_up() {
+	function are_all_wireless_interfaces_up() {
+		local num_up=$( ubus list hostapd.* | wc -l )
+		[ $( count_enabled_wifi_interfaces ) -eq $num_up ] && return 0 || return 1
 	}
 	while ! are_all_wireless_interfaces_up; do
 		logger -t "${NAME}" -pdaemon.info "Waiting for all Wi-Fi interfaces to initialize"
@@ -46,10 +55,8 @@ function create_own_rrm_nr_list() {
 }
 
 start_service() {
-	#[ ! -f /etc/config/wireless ] && logger -t "${NAME}" -pdaemon.error "/etc/config/wireless does not exist" && exit 1
-	#[ $(grep -q 'wifi-iface' /etc/config/wireless) ] && logger -t "${NAME}" -pdaemon.error "/etc/config/wireless does not have any wifi-iface stanzas" && exit 1
-
-	wait_until_all_wireless_interfaces_are_up
+	abort_when_no_enabled_wifi_interfaces
+	wait_until_all_enabled_wifi_interfaces_are_up
 
 	procd_open_instance
 	procd_set_param command /bin/sh "/usr/bin/rrm_nr"
